### PR TITLE
Update bamboozle.md

### PR DESCRIPTION
**Pull request by jlandrum**
The right thing to do.

### CODE REVIEW

**Comment by jessecurry** [comment]
We'll need to check with @austinmccarthy-haneke, @greghochsprung, @minhochoi, and @ThomasKomarnicki before we can merge this. Though, I'd tend to agree with this change.

**Comment by jessecurry** [comment]
Sorry, and @dtartaglia!

**Comment by jlandrum** [comment]
I say, all in favor, say yay. All opposed, pack your things and go.

**Comment by greghochsprung** [comment]
I had just merged in my order for that, so I say yay!

**Comment by minhochoi** [comment]
I am ok with this

**Comment by ThomasKomarnicki** [comment]
uhhhhh no thx :(

**Comment by jlandrum** [comment]
:(

**Pull request closed without merging**
